const fs=require('fs');const path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const root=path.resolve(__dirname,'..');const pw=[...fs.readFileSync(path.join(root,'ACCESOS-LOCALES.txt'),'utf8').matchAll(/Contraseña: (.+)/g)].map(x=>x[1].trim());const ok=[];
function check(v,n){if(!v)throw new Error(n);ok.push(n)}
async function login(browser,email,password){const c=await browser.newContext({viewport:{width:1440,height:900}}),p=await c.newPage();await p.goto('http://localhost:5088/Login');await p.locator('[name=email]').fill(email);await p.locator('[name=password]').fill(password);await Promise.all([p.waitForLoadState('networkidle'),p.getByRole('button',{name:'Ingresar',exact:true}).click()]);return {c,p}}
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});let originalName='';const temporary='Temporal-Usuario-2026';try{
 const admin=await login(browser,'admin@electricistas.local',pw[0]);check(admin.p.url().includes('/Catalogo'),'Administrador inicia sesión');await admin.p.goto('http://localhost:5088/UsuariosCatalogo');
 check(await admin.p.locator('.user-card').count()>=2,'Listado de usuarios');await admin.p.screenshot({path:path.join(root,'datos','etapa3-usuarios.png')});
 await admin.p.selectOption('.filters [name=rol]','asesor');await Promise.all([admin.p.waitForURL(/rol=asesor/),admin.p.getByRole('button',{name:'Buscar',exact:true}).click()]);check(await admin.p.locator('.user-card').count()>=1&&await admin.p.locator('.user-card').filter({hasText:'Administrador'}).count()===0,'Filtro por rol');
 await admin.p.goto('http://localhost:5088/UsuariosCatalogo');let card=admin.p.locator('.user-card').filter({hasText:'asesor@electricistas.local'});originalName=(await card.locator('.user-summary strong').textContent()).trim();await card.getByRole('link',{name:'Editar'}).click();
 await admin.p.locator('.user-editor [name=nombre]').fill('Asesor QA');await admin.p.locator('.user-editor [name=rol]').selectOption('admin');await admin.p.locator('.user-editor [name=password]').fill(temporary);await Promise.all([admin.p.waitForURL('**/UsuariosCatalogo'),admin.p.getByRole('button',{name:'Guardar cambios'}).click()]);
 card=admin.p.locator('.user-card').filter({hasText:'asesor@electricistas.local'});check(await card.getByText('Asesor QA',{exact:true}).count()===1&&await card.getByText('Administrador',{exact:true}).count()===1,'Edición de nombre y rol');
 const promoted=await login(browser,'asesor@electricistas.local',temporary);check(promoted.p.url().includes('/Catalogo')&&await promoted.p.locator('nav a[href="/UsuariosCatalogo"]').count()===1,'Restablecimiento de contraseña y rol aplicado');await promoted.c.close();
 await card.getByRole('link',{name:'Editar'}).click();await admin.p.locator('.user-editor [name=nombre]').fill(originalName);await admin.p.locator('.user-editor [name=rol]').selectOption('asesor');await admin.p.locator('.user-editor [name=password]').fill(pw[1]);await Promise.all([admin.p.waitForURL('**/UsuariosCatalogo'),admin.p.getByRole('button',{name:'Guardar cambios'}).click()]);
 card=admin.p.locator('.user-card').filter({hasText:'asesor@electricistas.local'});await Promise.all([admin.p.waitForURL('**/UsuariosCatalogo'),card.getByRole('button',{name:'Desactivar'}).click()]);check(await admin.p.locator('.user-card').filter({hasText:'asesor@electricistas.local'}).getByText('Inactivo',{exact:true}).count()===1,'Desactivación lógica');
 const blocked=await login(browser,'asesor@electricistas.local',pw[1]);check(blocked.p.url().includes('/Login')&&await blocked.p.getByRole('alert').count()===1,'Usuario inactivo no inicia sesión');await blocked.c.close();
 card=admin.p.locator('.user-card').filter({hasText:'asesor@electricistas.local'});await Promise.all([admin.p.waitForURL('**/UsuariosCatalogo'),card.getByRole('button',{name:'Activar'}).click()]);check(await admin.p.locator('.user-card').filter({hasText:'asesor@electricistas.local'}).getByText('Activo',{exact:true}).count()===1,'Reactivación');
 card=admin.p.locator('.user-card').filter({hasText:'admin@electricistas.local'});await card.getByRole('link',{name:'Editar'}).click();check(await admin.p.locator('.user-editor select[name=rol]').isDisabled()&&await admin.p.locator('.user-editor input[type=checkbox][name=activo]').isDisabled(),'Controles propios protegidos');
 const csrf=await admin.p.locator('.user-editor [name=csrf]').inputValue(),id=await admin.p.locator('.user-editor [name=id]').inputValue();const forged=await admin.p.request.post('http://localhost:5088/UsuariosCatalogo',{form:{csrf,id,nombre:'Administrador',email:'admin@electricistas.local',rol:'asesor',password:'',accion:'guardar'}});check(forged.status()===400,'Servidor impide degradar o desactivar la cuenta propia');
 const advisor=await login(browser,'asesor@electricistas.local',pw[1]);check((await advisor.p.request.get('http://localhost:5088/UsuariosCatalogo')).status()===403,'Asesor no accede al ABM');await advisor.c.close();
 await admin.p.setViewportSize({width:390,height:844});await admin.p.goto('http://localhost:5088/UsuariosCatalogo?editar=2');check(await admin.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'ABM móvil sin desbordamiento');await admin.p.screenshot({path:path.join(root,'datos','etapa3-usuarios-movil.png')});
 fs.writeFileSync(path.join(root,'datos','pruebas-etapa3.json'),JSON.stringify({passed:ok.length,checks:ok},null,2));console.log(`${ok.length} comprobaciones correctas.`);await admin.c.close();
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
