const fs=require('fs');const path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.APP_URL||'http://localhost:5090',name='Obra QA etapa 5';
const password=[...fs.readFileSync(path.join(root,'ACCESOS-LOCALES.txt'),'utf8').matchAll(/Contraseña: (.+)/g)][0][1].trim(),ok=[];
function check(value,label){if(!value)throw new Error(label);ok.push(label)}
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();let id=0;try{
 await page.goto(base+'/Login');await page.locator('[name=email]').fill('admin@electricistas.local');await page.locator('[name=password]').fill(password);await Promise.all([page.waitForURL('**/Catalogo'),page.getByRole('button',{name:'Ingresar',exact:true}).click()]);check(page.url().includes('/Catalogo'),'Inicio de sesión');
 const health=await page.request.get(base+'/salud');check(health.status()===200&&(await health.json()).estado==='ok','Endpoint de salud disponible');
 await page.goto(base+'/Presupuestos');while(await page.getByRole('link',{name,exact:true}).count()){const href=await page.getByRole('link',{name,exact:true}).first().getAttribute('href');await page.goto(base+href+'&confirmar=1');await Promise.all([page.waitForURL('**/Presupuestos'),page.getByRole('button',{name:'Sí, eliminar'}).click()]);}
 await page.goto(base+'/Catalogo?vista=tarjetas');for(let i=0;i<2;i++)await Promise.all([page.waitForURL(/Catalogo/),page.locator('.catalog-add').nth(i).getByRole('button',{name:/Agregar/}).click()]);await page.goto(base+'/Carrito');
 await page.locator('.work-name [name=nombre]').fill(name);await Promise.all([page.waitForURL('**/Carrito'),page.getByRole('button',{name:'Guardar nombre'}).click()]);check(await page.getByRole('button',{name:'Confirmar y generar orden'}).isEnabled(),'Confirmación habilitada');
 await Promise.all([page.waitForURL(/\/Presupuesto\?id=\d+/),page.getByRole('button',{name:'Confirmar y generar orden'}).click()]);id=Number(new URL(page.url()).searchParams.get('id'));check(id>0,'Orden guardada con número');check(await page.getByText('Orden generada correctamente. Ya podés descargar el PDF.').count()===1,'Confirmación visible');
 check(await page.getByText('Casa de electricidad',{exact:false}).count()===0,'Campo Casa de Electricidad eliminado');await page.screenshot({path:path.join(root,'datos','etapa5-orden.png'),fullPage:true});
 await page.goto(base+'/Presupuestos');check(await page.getByRole('link',{name,exact:true}).count()===1,'Orden disponible en historial');
 const pdf=await page.request.get(base+'/DescargarPdf?id='+id);check(pdf.status()===200&&pdf.headers()['content-type'].includes('application/pdf'),'Descarga PDF válida');const bytes=await pdf.body();fs.writeFileSync(path.join(root,'lista de compra de test.pdf'),bytes);const raw=bytes.toString('latin1');check(raw.startsWith('%PDF-1.4'),'Archivo PDF reconocido');check(raw.includes('TOTAL APROXIMADO ARS')&&raw.includes('Presupuesto aproximado'),'PDF incluye total y aviso');check(!raw.includes('Local:')&&!raw.toLowerCase().includes('casa de electricidad'),'PDF sin Casa de Electricidad');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/Presupuesto?id='+id);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Orden móvil sin desbordamiento');await page.screenshot({path:path.join(root,'datos','etapa5-orden-movil.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:900});await page.goto(base+'/Presupuesto?id='+id+'&confirmar=1');await Promise.all([page.waitForURL('**/Presupuestos'),page.getByRole('button',{name:'Sí, eliminar'}).click()]);check(await page.getByRole('link',{name,exact:true}).count()===0,'Orden temporal eliminada del historial');
 fs.writeFileSync(path.join(root,'datos','pruebas-etapa5.json'),JSON.stringify({passed:ok.length,checks:ok,pdf:'lista de compra de test.pdf'},null,2));console.log(`${ok.length} comprobaciones correctas. Orden temporal: ${id}.`);
}finally{await context.close();await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
