const fs=require('fs');const path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'playwright');
const root=path.resolve(__dirname,'..'),base=process.env.APP_URL||'http://localhost:5088',checks=[];
const password=[...fs.readFileSync(path.join(root,'ACCESOS-LOCALES.txt'),'utf8').matchAll(/Contraseña: (.+)/g)][0][1].trim();
function check(value,label){if(!value)throw new Error(label);checks.push(label)}
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();try{
 await page.addInitScript(()=>Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>false}));
 await page.goto(base+'/Login');await page.locator('[name=email]').fill('admin@electricistas.local');await page.locator('[name=password]').fill(password);await Promise.all([page.waitForURL('**/Catalogo'),page.getByRole('button',{name:'Ingresar',exact:true}).click()]);
 await page.goto(base+'/Presupuestos');check(await page.getByRole('heading',{name:'Solicitudes',exact:true}).count()===1,'Historial abre correctamente');check(await page.locator('.budget-overview>div').count()===3,'Resumen visible');check(await page.locator('.budget-filters [name=q]').count()===1,'Buscador disponible');check(await page.locator('.budget-filters [name=tipo]').count()===1,'Filtro por tipo disponible');check(await page.locator('.budget-filters [name=orden]').count()===1,'Ordenamiento disponible');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Sin desbordamiento en escritorio');
 const cards=page.locator('.budget-card');if(await cards.count()>0){const first=cards.first(),title=(await first.locator('h2').innerText()).trim(),detailHref=await first.getByRole('link',{name:'Abrir solicitud'}).getAttribute('href');check(await first.locator('.budget-number').isVisible(),'Número de solicitud visible');check(await first.locator('time').isVisible(),'Fecha y hora visibles');check(await first.getByRole('link',{name:'Descargar PDF'}).count()===1,'Descarga PDF directa');const aligned=await first.evaluate(e=>{const card=e.getBoundingClientRect(),actions=e.querySelector('.budget-card-actions').getBoundingClientRect();return Math.abs(card.left-actions.left)<=1&&Math.abs(card.right-actions.right)<=1});check(aligned,'Acciones ocupan el ancho de la tarjeta');await page.goto(base+detailHref+'&nueva=true');check(await page.getByRole('heading',{name:'Solicitud preparada correctamente'}).count()===1,'Confirmación de solicitud visible');check(await page.getByRole('link',{name:'Descargar PDF'}).count()===1,'Descarga disponible en el detalle');check(await page.getByRole('button',{name:'Enviar por WhatsApp'}).count()===1,'Acción WhatsApp disponible');check(await page.getByRole('button',{name:'Enviar por correo'}).count()===1,'Acción correo disponible');check((await page.getByRole('button',{name:'Enviar por WhatsApp'}).getAttribute('data-share-url')).startsWith('https://wa.me/'),'Mensaje de WhatsApp preparado');check((await page.getByRole('button',{name:'Enviar por correo'}).getAttribute('data-share-url')).startsWith('mailto:'),'Correo preparado');await page.screenshot({path:path.join(root,'datos','solicitud-preparada.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.goto(base+detailHref+'&nueva=true');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Detalle de solicitud sin desbordamiento en celular');await page.screenshot({path:path.join(root,'datos','solicitud-preparada-movil.png'),fullPage:false});await page.setViewportSize({width:1440,height:900});await page.goto(base+'/Presupuestos');await page.locator('[name=q]').fill(title);await Promise.all([page.waitForURL(url=>url.pathname==='/Presupuestos'&&url.searchParams.get('q')===title),page.getByRole('button',{name:'Aplicar'}).click()]);check(await page.locator('.budget-card').count()>=1,'Búsqueda encuentra la obra');check((await page.locator('.budget-card h2').first().innerText()).toLowerCase().includes(title.toLowerCase()),'Resultado coincide con búsqueda');}
 await page.goto(base+'/Presupuestos?orden=antiguos');const numbers=await page.locator('.budget-number').allInnerTexts();if(numbers.length>1)check(numbers[0].localeCompare(numbers[numbers.length-1])<=0,'Orden por antiguos funciona');
 await page.goto(base+'/Presupuestos');await page.screenshot({path:path.join(root,'datos','presupuestos-mejorado.png'),fullPage:false});await page.setViewportSize({width:390,height:844});await page.goto(base+'/Presupuestos');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Sin desbordamiento en celular');if(await page.locator('.budget-list').count())check(await page.locator('.budget-list').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length===1),'Tarjetas en una columna móvil');
 fs.writeFileSync(path.join(root,'datos','pruebas-presupuestos.json'),JSON.stringify({passed:checks.length,checks},null,2));console.log(`${checks.length} comprobaciones correctas.`);
}finally{await context.close();await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
